version: "3"
services:
  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 88:80/tcp
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ:-Etc/UTC}
      WEBPASSWORD: ${WEBPASSWORD:-pass}
    # Volumes store your data between container upgrades
    volumes:
      - ./pihole:/etc/pihole
      - ./dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
networks: {}
