version: "3"
services:
  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 88:80/tcp
    cap_add:
      - NET_ADMIN
    networks:
      - nano-server-net
    environment:
      TZ: ${TZ:-Europe/Moscow}
      WEBPASSWORD: ${WEBPASSWORD:-pass}
    # Volumes store your data between container upgrades
    volumes:
      - ./pihole:/etc/pihole
      - ./dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    labels:
      - homepage.group=Utils
      - homepage.name=PiHole
      - homepage.icon=pi-hole.svg
      - homepage.href=http://pihole.home/admin
      - homepage.description=DNS sink hole
      - homepage.widget.type=pihole
      - homepage.widget.url=http://pihole
      - homepage.widget.key=${HOMEPAGE_VAR_PIHOLE_API_TOKEN:-pony}
networks:
  nano-server-net:
    external: true
