services:
  luanti:
    image: lscr.io/linuxserver/luanti:latest
    labels:
      - autoheal-app=true
      - com.centurylinklabs.watchtower.enable=true
    container_name: ${CONTAINER_NAME}_main
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Moscow}
      - "CLI_ARGS=--gameid devtest"
    volumes:
      - ./${CONTAINER_NAME}_data/config:/config/.minetest:z
    restart: unless-stopped
    network_mode: service:gluetun_luanti
    depends_on:
      gluetun_luanti:
        condition: service_healthy
        restart: true
  #
  # VPN
  #
  gluetun_luanti:
    extends:
      file: ../../available/gluetun/gluetun-compose-base.yaml
      service: gluetun-amnezia
    volumes:
      - ./${CONTAINER_NAME}_data/gluetun:/gluetun:Z
    environment:
      HTTP_CONTROL_SERVER_ADDRESS: :8002
      FIREWALL_INPUT_PORTS: 30000
    ports:
      - 30000:30000/udp
#
# NetWorks
#
networks: {}
