services:
  3proxy:
    image: 3proxy/3proxy:latest
    container_name: ${CONTAINER_NAME}_main
    labels:
      # watchtower
      com.centurylinklabs.watchtower.enable: true
      # traefik
      traefik.enable: "true"
      traefik.tcp.routers.proxy.rule: "HostSNI(`proxy.${DOMAIN}`)"
      traefik.tcp.routers.proxy.entrypoints: "websecure"
      traefik.tcp.routers.proxy.tls: "true"
      traefik.tcp.routers.proxy.tls.certresolver: "letsencrypt"
      traefik.tcp.services.proxy.loadbalancer.server.port: "1080"
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Europe/Moscow}
    volumes:
      - ./${CONTAINER_NAME}_data/3proxy.cfg:/etc/3proxy/3proxy.cfg:ro
    networks:
      traefik: {}
  #
  # BeckUps
  #
  ## main
  backup_restic_proxy:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: backup
    volumes:
      - ./${CONTAINER_NAME}_data:/backup_data:ro,z
    environment:
      BACKUP_CRON: "0 38 3 * * *"
  ## prune
  prune_restic_proxy:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: prune
  ## chekc
  check_restic_proxy:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: check
    environment:
      CHECK_CRON: "0 30 5 * * *"
#
# NetWorks
#
networks:
  apprise_notification: 
    external: true
  traefik:
    external: true
