services:
  3proxy:
    image: 3proxy/3proxy:latest
    container_name: ${CONTAINER_NAME}_proxy
    labels:
      # watchtower
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Europe/Moscow}
    ports:
      - "1080:1080"
    volumes:
      - ./${CONTAINER_NAME}_data/3proxy.cfg:/etc/3proxy/3proxy.cfg:ro
  mtproto:
    image: telegrammessenger/proxy:latest
    container_name: ${CONTAINER_NAME}_mtproto
    labels:
      # watchtower
      com.centurylinklabs.watchtower.enable: true
      # traefik
      traefik.enable: "true"
      traefik.http.routers.mtproto-stats.rule: "Host(`mtproxy.${DOMAIN}`)"
      traefik.http.routers.mtproto-stats.entrypoints: "websecure"
      traefik.http.routers.mtproto-stats.tls.certresolver: "letsencrypt"
      traefik.http.routers.mtproto-stats.middlewares: "auth@docker"
      traefik.http.services.mtproto-stats.loadbalancer.server.port: "2398"
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Europe/Moscow}
    ports:
      - "8443:443"
    volumes:
      - ./${CONTAINER_NAME}_data/mtproto:/data
    networks:
      - traefik
  #
  # BeckUps
  #
  ## main
  backup_restic_proxy:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: backup
    volumes:
      - ./${CONTAINER_NAME}_data:/backup_data:ro,z
    environment:
      BACKUP_CRON: "0 38 3 * * *"
      PRE_COMMANDS: ""
      POST_COMMANDS_SUCCESS: ""
  ## prune
  prune_restic_proxy:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: prune
  ## chekc
  check_restic_proxy:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: check
    environment:
      CHECK_CRON: "0 30 5 * * *"
#
# NetWorks
#
networks:
  apprise_notification: 
    external: true
  traefik: 
    external: true
