services:
  memos:
    image: neosmemo/memos:stable
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    container_name: memos
    restart: unless-stopped
    volumes:
      - ./memos-data/:/var/opt/memos
    ports:
      - 5230:5230
