---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Utils:
    - dockge:
        icon: dockge-light.svg
        href: http://dockge.home
        description: Docker manager
        server: nano-server
        container: dockge-dockge-1
    - uptime-kuma:
        icon: uptime-kuma.svg
        href: http://uptime-kuma.home
        description: Uptime life checker
        server: nano-server
        container: uptime-kuma-uptime-kuma-1

- Media:
    - qbittorrent:
        icon: qbittorrent.svg
        href: http://torrent.home
        description: Torrent downloader
        server: nano-server
        container: qbittorrent
