---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    label: System
    cpu: true
    cputemp: true
    memory: true

- resources:
    label: Storage
    expanded: true
    disk:
      - /mnt/root
      - /mnt/ssd

- search:
    provider: brave
    target: _blank
