services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: ${CONTAINER_NAME}_main
    labels:
      - autoheal-app=true
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    volumes:
      - /media/jellyfin/Books/Audiobooks:/audiobooks:Z
      - /media/jellyfin/Podcast:/podcasts:Z
      - ./${CONTAINER_NAME}_data/config/config:/config:z
      - ./${CONTAINER_NAME}_data/config/metadata:/metadata:Z
    environment:
      TZ: ${TZ:-Europe/Moscow}
    network_mode: service:gluetun_abs
    depends_on:
      gluetun_abs:
        condition: service_healthy
        restart: true
  #
  # VPN
  #
  gluetun_abs:
    extends:
      file: ../gluetun/gluetun-compose-base.yaml
      service: gluetun
    volumes:
      - ./${CONTAINER_NAME}_data/gluetun:/gluetun:Z
    environment:
      HTTP_CONTROL_SERVER_ADDRESS: :8002
    ports:
      - 13378:80
      - 13379:8000
  #
  # BeckUps
  #
  ## main
  backup_restic__audiobookshelf:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: backup
    volumes:
      - ./${CONTAINER_NAME}_data/config:/backup_data:ro,z
    environment:
      BACKUP_CRON: "0 35 3 * * *"
  ## prune
  prune_restic__audiobookshelf:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: prune
  ## chekc
  check_restic__audiobookshelf:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: check
    environment:
      CHECK_CRON: "0 25 5 * * *"
#
# NetWorks
#
networks:
  apprise_notification:
    external: true
