services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: ${CONTAINER_NAME}_main
    labels:
      - autoheal-app=true
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    volumes:
      - /hdd_data/audiobookshelf/audiobooks:/audiobooks:Z
      - /hdd_data/audiobookshelf/podcast:/podcasts:Z
      - ./${CONTAINER_NAME}_data/config/config:/config:z
      - ./${CONTAINER_NAME}_data/config/metadata:/metadata:Z
    environment:
      TZ: ${TZ:-Europe/Moscow}
    network_mode: service:amneziawg_abs
    depends_on:
      amneziawg_abs:
        condition: service_healthy
        restart: true
  #
  # VPN
  #
  amneziawg_abs:
    extends:
      file: ../../available/amneziawg/amneziawg-compose-base.yaml
      service: amneziawg-client
    volumes:
      - ./${CONTAINER_NAME}_data/amneziawg:/config:Z
    ports:
      - 13378:80
      - 13379:8000
  #
  # BeckUps
  #
  ## main
  backup_restic__audiobookshelf:
    extends:
      file: ../../available/restic/restic-compose-base.yaml
      service: backup
    volumes:
      - ./${CONTAINER_NAME}_data/config:/backup_data:ro,z
    environment:
      BACKUP_CRON: "0 35 3 * * *"
  ## prune
  prune_restic__audiobookshelf:
    extends:
      file: ../../available/restic/restic-compose-base.yaml
      service: prune
  ## chekc
  check_restic__audiobookshelf:
    extends:
      file: ../../available/restic/restic-compose-base.yaml
      service: check
    environment:
      CHECK_CRON: "0 25 5 * * *"
#
# NetWorks
#
networks:
  apprise_notification:
    external: true
