version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    environment:
      DOCKGE_STACKS_DIR: ${DOCKGE_STACKS_DIR:-/tmp}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ${DOCKGE_STACKS_DIR:-/tmp}:${DOCKGE_STACKS_DIR:-/tmp}
