services:
  podgrab:
    image: akhilrex/podgrab
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
      - PASSWORD=${PASSWORD:-password}
    volumes:
      - ./podgrab_data/config:/config
      - /media/jellyfin/Podcast:/assets
    ports:
      - 8642:8080
    restart: unless-stopped
